### ISSUE TITLE
 Could not initialize WebGPU scene.  Error: WebGPU not supported

### ISSUE THREAD

**Issue by loorlab** [anvaka/vector-space-adventure#1]
Hi Friend, your url https://anvaka.github.io/vector-space-adventure/ not working :(

Could not initialize WebGPU scene.

Error: WebGPU not supported

Regards !

**Comment by anvaka** [comment]
Make sure you are using a browser and device that supports webgpu. E.g. latest version of chrome typically has the support.

**Comment by loorlab** [comment]
> Make sure you are using a browser and device that supports webgpu. E.g. latest version of chrome typically has the support.

Oh yeahh Chrome Working.

Your work is incredible.

✨
